# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('author', 'author')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='超级用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(max_length=100, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(max_length=100, verbose_name='头像地址'),
        ),
    ]
