# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_auto_20170424_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
